title: CERA
description: A Community-Driven Platform for Enhancing Utility Safety
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman


# show_sidebar: true

# # Menu

# navigation:                # accepts {file, title, url, icon, sidebaricon}
#   - {file: "index.md", title: Home}